spring:
  application:
    name: App
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/automobiles
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs.yaml

server:
  port: 8080
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework: info
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
